import { Typography } from "@mui/material";

export const generateMetadata = () => {
  return {
    title: "orders",
    description: "Generated by create next app",
  };
};

export default function OrdersPage() {
  return (
    <main>
      <Typography component="p">orders</Typography>
    </main>
  );
}
