import AppProvider from "@/components/app-provider";
import AppSidebar from "@/components/app-sidebar";
import { defaultMetadata } from "@/shared/constants/default-metadata";
import { Metadata } from "next";
import styles from "@/styles/root-layout.module.scss";

export const metadata: Metadata = {
  ...defaultMetadata,
  title: "root layout",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <AppProvider>
      <main className={styles.main}>
        <AppSidebar />
        {children}
      </main>
    </AppProvider>
  );
}
