import AppProvider from "@/components/app-provider";
import AppSidebar from "@/components/app-sidebar";
import { defaultMetadata } from "@/shared/constants/default-metadata";
import { Metadata } from "next";
import AppHeader from "@/components/app-header";
import { Box } from "@mui/material";

export const metadata: Metadata = {
  ...defaultMetadata,
  title: "root layout",
  description: "Generated by create next app",
};

export default function Layout({ children }: { children: React.ReactNode }) {
  return (
    <AppProvider>
      <Box component={"main"} sx={{ display: "flex" }}>
        <AppSidebar />
        <Box sx={{ margin: "0 16px", flexGrow: 1 }}>
          <AppHeader />
          {children}
        </Box>
      </Box>
    </AppProvider>
  );
}
