import { Metadata } from "next";
import { AppProvider } from "../../providers/app-provider";
import { Sidebar } from "@/widgets/sidebar";
import { defaultMetadata } from "@/shared/config";
import { getSidebarData } from "@/entities/sidebar";

export const metadata: Metadata = {
  ...defaultMetadata,
  title: "root layout",
  description: "Generated by create next app",
};

export async function RootLayout({ children }: { children: React.ReactNode }) {
  const sidebarItems = await getSidebarData();
  return (
    <AppProvider>
      <main>
        <Sidebar sidebarItems={sidebarItems} />
        {children}
      </main>
    </AppProvider>
  );
}
