import { Metadata } from "next";
import { AppProvider } from "../../providers/app-provider";
import { defaultMetadata } from "@/shared/config/defaultMetadata";
import { Sidebar } from "@/widgets/sidebar";

export const metadata: Metadata = {
  ...defaultMetadata,
  title: "root layout",
  description: "Generated by create next app",
};

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <AppProvider>
      <main className={"flex"}>
        <Sidebar />
        {children}
      </main>
    </AppProvider>
  );
}
