import { Metadata } from "next";
import { AppProvider } from "../../providers/app-provider";
import { defaultMetadata } from "@/shared/config/defaultMetadata";

export const metadata: Metadata = {
  ...defaultMetadata,
  title: "root layout",
  description: "Generated by create next app",
};

export function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
