import type { Metadata } from "next";
import "@/styles/global.scss";
import Head from "next/head";
import { InitColorSchemeScript } from "@mui/material";

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export const metadata: Metadata = {
  title: "global",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <head>
        <link
          href="https://fonts.googleapis.com/icon?family=Material+Icons"
          rel="stylesheet"
        ></link>
      </head>
      <body>
        <InitColorSchemeScript attribute="class" />
        {children}
      </body>
    </html>
  );
}
