import type { Metadata } from "next";
import { AppProvider } from "../../providers/app-provider";
import "../../styles";

export const viewport = {
  width: "device-width",
  initialScale: 1,
  maximumScale: 1,
};

export const metadata: Metadata = {
  title: "global",
  description: "Generated by create next app",
};

export function GlobalLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru" suppressHydrationWarning>
      <body>
        <AppProvider>{children}</AppProvider>
      </body>
    </html>
  );
}
